### ISSUE TITLE
[SMAC v1] Comparing with SMAC v1

### ISSUE THREAD

**Issue by Jiwonjeon9603** [oxwhirl/smacv2#30] opened 2023-09-05 04:46 UTC
Hi, thanks for providing SMAC v2!!

I have one questions comparing with SMAC v1.

Can we use SMAC 1 env in SMAC v2? For example, I want to run 3m, 2s_vs_3z, etc in SMAC v1.

I tried to learn SMAC v1 maps in SMAC v2, so I run env-config with sc2.py in SMAC V1 github.

But It dosen't start training, and giving same message as below.

<img width="1311" alt="스크린샷 2023-09-05 오후 1 45 15" src="https://github.com/oxwhirl/smacv2/assets/53930598/122968a1-f645-48c5-a528-50a3dfc73e32">

How can I run smac 1 maps(3m, 2s_vs_3z, etc) in smac v2?

Thanks!

**Comment by benellis3** [comment] 2023-09-08 10:02
Hi. So because of changes to the way that we start SMACv2, SMACv1 maps are not compatible with SMACv2. You *can* recreate them by using the `FixedDistribution` distribution type in `distributions.py`, but they won't be exactly the same because the heuristic AI is also different between SMACv1 and SMACv2. If you want to actually run SMACv1 maps in SMACv2, the correct way of doing that is to `import smac` just as before, and then separately importing `smacv2`.

I haven't tested this use case very much though so if you run into anything let me know!

**Comment by benellis3** [comment] 2023-11-23 14:54
Closing but please reopen if you have more issues

**Closed by benellis3** 2023-11-23 14:54 UTC

**Comment by thomasbbrunner** [comment] 2024-09-18 11:29
@benellis3 Isn't it rather confusing that the SMACv1 maps are included in the SMACv2 [SMAC_Maps](https://github.com/oxwhirl/smacv2/tree/main/smacv2/env/starcraft2/maps/SMAC_Maps) folder, if they are not supported?

Also, it seems that there is no explicit error message when attempting to use a SMACv1 map in SMACv2. Is this by design?
